apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - name: unifi-controller
          image: jacobalberty/unifi:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "8G"
              cpu: "6000m"
          ports:
            - name: "l2-discoverable"
              containerPort: 1900
              protocol: UDP
            - name: "stun"
              containerPort: 3478
              protocol: UDP
            - name: "ap-discovery"
              containerPort: 10001
              protocol: UDP
            - name: "speed-test"
              containerPort: 6789
            - name: "internal-comms"
              containerPort: 8080
            - name: "unknown-port"
              containerPort: 8081
            - name: "http-web"
              containerPort: 8443
            - name: "http-s-redirect"
              containerPort: 8843
            - name: "http-redirect"
              containerPort: 8880
          volumeMounts:
            - mountPath: /unifi
              name: vol1
      volumes:
        - hostPath:
            path: /mnt/data/unifi-controller
            type: DirectoryOrCreate
          name: vol1
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: uckey
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.10.241
  selector:
    app: unifi-controller
  ports:
    - name: "speed-test"
      protocol: TCP
      targetPort: 6789
      port: 6789
    - name: "internal-comms"
      protocol: TCP
      targetPort: 8080
      port: 8080
    - name: "unknown-port"
      protocol: TCP
      targetPort: 8081
      port: 8081
    - name: "http-web"
      protocol: TCP
      targetPort: 8443
      port: 8443
    - name: "http-s-redirect"
      protocol: TCP
      targetPort: 8843
      port: 8843
    - name: "http-redirect"
      protocol: TCP
      targetPort: 8880
      port: 8880
    - name: "local-comms"
      protocol: TCP
      targetPort: 27117
      port: 27117
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-service-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: uckey
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.10.241
  selector:
    app: unifi-controller
  ports:
    - name: "l2-discoverable"
      protocol: UDP
      targetPort: 1900
      port: 1900
    - name: "stun"
      protocol: UDP
      targetPort: 3478
      port: 3478
    - name: "ap-discovery"
      protocol: UDP
      targetPort: 10001
      port: 10001
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
spec:
  podSelector: {}
  egress:
    - {}
  policyTypes:
    - Egress